### ISSUE TITLE
Lmod PATH configuration

### ISSUE THREAD

**Issue by statiksof** [cmd-ntrf/jupyter-lmod#12]
Hi, I am trying to enable the extension on jupyterlab which works now. 
The problem is that it does not show the correct available modules but something else like:

```chunk, function, etc```

Do I need to export some env variables?

**Comment by cmd-ntrf** [comment]
Are you able to call module commands from a terminal in JupyterLab?

jupyter-lmod works by calling lmod with Popen, therefore all environement variables required by LMOD need to be defined before launching jupyterlab. 

If the output of the Popen call does not correspond to modules because of a misconfiguration, jupyter-lmod is unfortunately unable at the moment to know it and therefore shows whatever is output by lmod or lua as module.

**Comment by statiksof** [comment]
@cmd-ntrf I tried some lmod commands from the jupyterlab terminal and it works.
